site_name: Dublin Electricity Modelling
site_description: 'Estimated Annual & Peak Electricity Demands by SA, map displayed via Tableau'
repo_name: 'codema-dev/dublin-webmaps'
repo_url: 'https://github.com/codema-dev/dublin-webmaps'
theme: readthedocs